### ISSUE TITLE
Can't choose which network adapter to bind to?

### ISSUE THREAD

**Issue by wearysky** [binarymaster/rdpwrap#20]
First off, thanks for creating this.  Made it much simpler to enable RDP on my Win8.1 Home install, so that I don't have to do a clean install of Win8.1 Pro.

Now to the problem - it seems that only one Network adapter is bound to RDPWrap - I'd like to be able to choose which one to use (or even better, let me choose priority, so that if one is disconnected, it binds to the other).  I can't seem to find any way to do this?

**Comment by binarymaster** [comment]
Since RDP Wrapper is just a layer between SCM and TS, it isn't responsible for such things.

Terminal Services listens on all interfaces by default.
Check the line 0.0.0.0:3389 LISTENING with command: netstat -a -n -p tcp

Anything else is controlled by system firewall (Windows Firewall or third party software).

**Comment by wearysky** [comment]
Ahh, I just figured it out - on my new laptop, when I connect the USB ethernet adaptor it disconnects the wifi adaptor.  Whereas on my old laptop, ethernet and wifi would co-exist.  Possibly a setting in Windows 8.1 that wasn't there in Windows 7.

**Comment by binarymaster** [comment]
Yes, beginning with Windows 8, when you connect ethernet interface, wireless interface goes inactive.

I think it can be configured somehow, but I don't know how exactly.
