### ISSUE TITLE
Rdp Shadowing Windows 8/8.1

### ISSUE THREAD

**Issue by Harbuz** [binarymaster/rdpwrap#30]
How do I enable shadowing?
From rdp config is set to allow but I can't shadow...

Regards,

**Comment by bvbmedia** [comment]
I'm looking for this feature as well. Is it possible in Windows 8.X?

**Comment by bvbmedia** [comment]
I've got it working.

1) Group Policy
You must first open the group policy editor and allow Full Control without user's permission.
Press: windows key + r then paste: Gpedit.msc and press enter.

Find this rule: Sets rules for remote control of Remote Desktop Services user sessions
Enable the rule and add the option: Full Control without user's permission

Press OK and you can close the window

![screenshot - 8-7-2015 15_18_11](https://cloud.githubusercontent.com/assets/3802035/8571040/9ebf9990-2584-11e5-8b9b-5ff531b1c637.png)

2) open CMD with administrative privileges

To show all sessions type: query user

If you want to shadow session_id 3 then you type:

C:\Windows\System32\mstsc.exe /shadow:3 /noConsentPrompt

If you want to have control type:
C:\Windows\System32\mstsc.exe /shadow:3 /control /noConsentPrompt

Let me know if it works for you too!

**Comment by binarymaster** [comment]
Since Windows 8.1 Basic Edition doesn't have gpedit.msc, you may use this command to change shadowing group policy:
`reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services" /v Shadow /t REG_DWORD /d X /f`

Where X is:
* 0 - disable shadowing
* 1 - control with permission
* 2 - control without permission
* 3 - view only with permission
* 4 - view only without permission

This will work.

**Comment by bvbmedia** [comment]
I'm using Windows 8.1 Pro and you can open: Edit Group Policy to do it
