### ISSUE TITLE
Windows 10 build 10525 not supported :(

### ISSUE THREAD

**Issue by brunobola** [binarymaster/rdpwrap#55]
Can u please update it to the new Windows 10 Build.
Thanks for your awesome work.

**Comment by Duken30** [comment]
I can confirm this as well. I have uploaded my termsrv.dll I would really love to get this working! I tried following the youtube tutorial, but I think that this is too different than the version you are working on in the video even using IDA Pro etc.

I just recently gave this a shot with Windows 10 Consumer Preview Build 10525 and the newer 10532. I can't seem to get it to work with this build. Any help would be greatly appreciated. I think it is because of the version of the termsrv.dll I have included a link to the dll.

http://wikisend.com/download/456260/termsrv.dll

**Comment by binarymaster** [comment]
Added support for build 10.0.10586.0, so build 10525 is already outdated.
